[Visualizaton]
p = 0

[SimSpace]
grid_size = [ 11, 11,]
visual_size = [ 800, 800,]
time_step = 0.01
max_steps = 75
global_brightness = 0.2
global_temperature = 0.5
population_consumers = 20
population_producers = 50
min_survival_rate = 0.25

[Producer]
size_consumption_rate = 0.0
num_species = 1
rgb = [ 0.0, 0.96, 0.0,]
sensory_range = 3
genome = -1
num_genomes = 4
num_neurons = 3
reproduce_mode = 1
mutation_rate = 0.2

[Consumer]
size_consumption_rate = 0.2
num_species = 2
rgb = [ 0.96, 0.5, 0.0,]
init_speed = 1
sensory_range = 5
num_observations = 17
num_actions = 10
genome = -1
num_genomes = 4
num_neurons = 3
reproduce_mode = 0
mutation_rate = 0.2
