[SimSpace]
grid_size = [50, 50]
visual_size = [800, 800]
time_step = 0.1
max_generations = 20
max_steps = 50
population = 50

[Producer]
rgb = [0.5, 0.96, 0.0]
sensory_range = 3
num_observations = 16
num_actions = 9
genome = -1
num_genomes = 4
num_neurons = 3
reproduce_mode = 1
mutation_rate = 0.2

[Consumer]
rgb = [0.96, 0.5, 0.0]
init_speed = 1
sensory_range = 3
num_observations = 16
num_actions = 9
genome = -1
num_genomes = 4
num_neurons = 3
reproduce_mode = 1
mutation_rate = 0.2